# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/sdk:10.0-preview AS build

WORKDIR /app

COPY . .
RUN dotnet publish -c Release -o /out Background/Background.csproj


# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:10.0-preview

WORKDIR /app
COPY --from=build /out ./

RUN apt-get update && apt-get install -y ffmpeg

ENV ENV_PROJECT_NAME "./Background"

CMD $ENV_PROJECT_NAME