apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-data
  namespace: woolball
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 5Gi
